# 1.7 Introduction to NumPy

## Creating arrays

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [10]:
a[2] = 10

In [11]:
a

array([ 1,  2, 10,  5,  7, 12])

In [13]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional Arrays

In [20]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [27]:
n[0,1] = 20

In [28]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
 n[2] = [1,1,1]

In [32]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [36]:
n[:, 2] = [0, 1, 2]

In [37]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

In [43]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [41]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [42]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [44]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2)) 

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [45]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [51]:
b = (10 + (a * 2)) ** 2 / 100

In [53]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [54]:
a / b+ 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison operations

In [56]:
a

array([0, 1, 2, 3, 4])

In [55]:
a >= 2

array([False, False,  True,  True,  True])

In [57]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [58]:
a > b

array([False, False,  True,  True,  True])

In [59]:
a[a > b]

array([2, 3, 4])

## Summarizing operations

In [61]:
a

array([0, 1, 2, 3, 4])

In [62]:
a.min()

np.int64(0)

In [63]:
a.max()

np.int64(4)

In [64]:
a.sum()

np.int64(10)

In [65]:
a.mean()

np.float64(2.0)

In [66]:
a.std()

np.float64(1.4142135623730951)

In [67]:
n.min()

np.int64(0)